name: talent_insider_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  get_it: ^8.0.3
  shared_preferences: ^2.3.5
  intl: ^0.20.1
  chewie: 1.8.5
  video_player: ^2.9.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

